### ISSUE TITLE
Cycles in hierarchy 

### ISSUE THREAD

**Issue by simonjupp** [enanomapper/ontologies#69] opened 2016-08-24 13:13 UTC
We've noticed that there are some cycles in the ontology hierarchy. See screenshot below from Protege. A lot of classes are being inferred equivalent that probably shouldn't be. e.g. toxicity == 'unsupervised learning'. 

![screenshot 2016-08-24 14 03 08](https://cloud.githubusercontent.com/assets/385021/17931576/1816afc6-6a04-11e6-844a-8dc68f292a58.jpeg)

We also noticed some of the URIs looked wrong e.g.  http://purl.enanomapper.org/onto/http://semanticscience.org/resource/CHEMINF_000123 asserted in iao-ext.owl

**Comment by JKChang2015** [comment] 2016-09-05 20:04
1. Cycles caused by assigning duplicate URI to the new classes in iao-ext.owl, it will be fixed in the next release.
2. Due to fail to load cheminf ontology, wrong URIs will be fixed after reload cheminf.owl.

**Comment by JKChang2015** [comment] 2016-09-06 09:52
fixed

**Closed by JKChang2015** 2016-09-06 09:52 UTC
Labels: bug
